name: Weekly test

on:
  schedule:
    - cron: '0 12 * * 5'  # Runs every Friday at 20:00 Beijing time
  workflow_dispatch:
  workflow_call:

jobs:
  weekly-test:
    uses: ./.github/workflows/test-package.yml
